export {default as Navbar} from './layout/Navbar'

export {default as ChannelDetails} from './channels/ChannelDetails'
export {default as Feed} from './Feed'
export {default as VideoDetails} from './videoComponents/VideoDetails'
export {default as SearchFeed} from './search/SearchFeed'
export { default as Searchbar } from './search/Searchbar'
export { default as Sidebar } from './layout/Sidebar'
export { default as Videos } from './videoComponents/Videos'
export { default as ChannelCard } from './channels/ChannelCard'
export {default as CommentCard} from'./comment/CommentCard'
export { default as VideoCard } from './videoComponents/VideoCard'
export{default as Comment} from './comment/Comment'

export{default as Login} from './authenticat/Login'
export{default as UploadVideo} from './videoComponents/UploadVideo'
export{default as YourChannel} from './channels/YourChannel'
export{default as Settings} from './settings/Settings'
export{default as NavbarAuth} from './authenticat/NavbarAuth'
export {default as Signup} from './authenticat/Signup'
